import re
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import spacy


pd.set_option('display.max_colwidth', None)

corpus = [
    "@@77495956 @6195956/ <h> What 's involved <p> Informed consent : a fieldworker will explain all the sessions to you and answer any questions you may have . Then they will ask you to complete and sign a consent form . You choose how much or how little you 'd like to do and you can withdraw from any or all of the sessions at any time . <p> Fasting blood sample : giving blood after not having eaten or drunk anything apart from water for at least six hours . <p> Urine sample:giving a small urine ( pee ) sample ( about 1/3 of a cup ) . <p> Chlamydia screening : if you give us a urine sample , we will ask if you would like to have it tested for chlamydia and gonorrhoea by the National Chlamydia Screening Programme ( NCSP ) . <p> Liver scan : having your liver scanned by ultrasound while you are lying on your back . <p> Time for a break : after doing all or any combination of the above sessions it 's time for a break and a light meal in our @ @ @ @ @ @ @ @ @ @ body 's size , shape and posture measured while standing up in a three-dimensional ( 3D ) machine that uses light scanners and computer software to produce the 3D image . There is no X-ray or radiation involved . <p> DEXA scan : having first your whole body , then just your hip , measured while lying on your back on a scanning machine . <p> Blood pressure and pulse : having your blood pressure and pulse measured in different ways while you are sitting and standing . <p> Lung function : blowing into a mouthpiece for as long and as hard as you can , once before and once after inhaling an asthma drug called salbutamol ( Ventolin ) . You can choose not to have the salbutamol in which case we will just ask you to blow into the mouthpiece once . <p> Interviews and computer tasks : answering questions ( some face-to-face , some on a computer ) about a range of topics and completing tasks on a computer that look at your memory and how you make decisions and react emotionally to certain situations . <p> @ @ @ @ @ @ @ @ @ @ and other official records if you are happy to and have n't already done so in the past . <p> Once you have completed your visit , which should take about four and a half hours , we will reimburse you for your travel expenses and give you a 30 shopping voucher to compensate you for your time .",
    "@@77495957 @6195957/ <h> COCO90s <p> Children of the 90s is a group of around 14,500 children born in the Avon area in 1991 and 1992 . Scientists have been studying them ever since and are constantly making discoveries that make a difference to lives around the world . <p> Some now have children of their own , and we want to follow these pregnancies , births and babies . We call this Children of the Children of the 90s , or COCO90s for short . This is the only project we know of that provides scientists with information on three generations , allowing them to study important social and health issues . <p> If you or your partner are in Children of the 90s and are about to become or are already a parent , we 'd love you , your partner and all your children to take part in COCO90s . It does n't  matter how much or how little you have been involved in Children of the 90s in the past -- this is a new opportunity to be involved in ground-breaking research . <h> How to enrol <p> @ @ @ @ @ @ @ @ @ @ your name and date of birth to 07772 102649 or email **30;0;TOOLONG and someone will call you back for a chat . <p> You 're doing something for science and are involved in new discoveries . It makes you feel a bit valuable . And it 's good for the kids to be involved from an early age so they can look back and say I was a part of it and did help in a small way .",
    "@@77495961 @6195961/ <h> Accommodation for new undergraduates <h> Undergraduate residences <p> Our residences provide so much more than just accommodation . With pastoral support and 24-hour security , opportunities to get involved in green initiatives , drama and music productions or sporting activities and a great social calendar . <h> Information for ... <p> If University accommodation is n't for you , we advise looking at Bristol 's commercial accommodation providers . Many have studios , ideal for anyone looking for a more independent lifestyle to that available in University-allocated accommodation . ",
    "@@77495957 @6195957/ <h> COCO90s <p> Children of the 90s is a group of around 14,500 children born in the Avon area in 1991 and 1992 . Scientists have been studying them ever since and are constantly making discoveries that make a difference to lives around the world . <p> Some now have children of their own , and we want to follow these pregnancies , births and babies . We call this Children of the Children of the 90s , or COCO90s for short . This is the only project we know of that provides scientists with information on three generations , allowing them to study important social and health issues . <p> If you or your partner are in Children of the 90s and are about to become or are already a parent , we 'd love you , your partner and all your children to take part in COCO90s . It does n't  matter how much or how little you have been involved in Children of the 90s in the past -- this is a new opportunity to be involved in ground-breaking research . <h> How to enrol <p> @ @ @ @ @ @ @ @ @ @ your name and date of birth to 07772 102649 or email **30;0;TOOLONG and someone will call you back for a chat . <p> You 're doing something for science and are involved in new discoveries . It makes you feel a bit valuable . And it 's good for the kids to be involved from an early age so they can look back and say I was a part of it and did help in a small way . ",
    "@@77495961 @6195961/ <h> Accommodation for new undergraduates <h> Undergraduate residences <p> Our residences provide so much more than just accommodation . With pastoral support and 24-hour security , opportunities to get involved in green initiatives , drama and music productions or sporting activities and a great social calendar . <h> Information for ... <p> If University accommodation is n't for you , we advise looking at Bristol 's commercial accommodation providers . Many have studios , ideal for anyone looking for a more independent lifestyle to that available in University-allocated accommodation . ",
    "@@77495962 @6195962/ <p> We use the ' applying from ' school code or the education history on your UCAS form to determine your eligibility for a contextual offer . It is the applicant 's responsibility to ensure these are correct . <p> It is important to stress that a school/college 's inclusion on the contextual offer list is not a judgement of the quality of the school or college . We recognise that many of the schools and colleges on the list have been deemed outstanding in many respects . <h> Admissions tests <p> UK Clinical Aptitude Test ( UKCAT ) You need to take the UKCAT test if you are applying for a medical or dental degree at Bristol . <p> National Admissions Test for Law ( LNAT ) You need to take the LNAT test if you are applying for a Law LLB course . We can not offer you a place until you have taken the test , unless the test is unavailable in your country of residence . ",
    "@@77495965 @6195965/ <h> Accommodation fees - what you pay <h> Accommodation fees <p> The accommodation fee you pay depends on the type of room you have . We have a very wide variety of accommodation , and so the fees are varied too . Fees are calculated using a number of factors including room size , whether you have a basin , or en suite , facilities at your residence such as common rooms and bars , gardens and sports facilities , any enhancement to your room , and catering . The fee also includes all gas , electricity and water rates , plus internet and a bus pass . Accommodation fees for 2017/18 are published on each residence page and are available to download below . <h> JCR fee <p> Each residence has a Junior Common Room ( JCR ) , a committee run by students that organises social and sporting events . All students moving into University-allocated accommodation pay a fee of around 50 towards their JCR , which goes towards funding the social events provided by your residence throughout the year . This one-off charge is compulsory and @ @ @ @ @ @ @ @ @ @ costs <p> All University allocated accommodation comes with compulsory basic contents insurance . The policy you are covered by and the cost of the insurance varies according to which residence you are in . It is vital that you check your policy and ensure that the cover is suitable for your needs . Bicycles are not usually covered as standard and you should top-up your insurance to cover your bicycle , for example . ",
    "@@77495966 @6195966/ <h> The Practice of Management <h> Unit description <p> The Practice of Management is a unit designed to make the transition from abstract theory to applied management practice . Students integrate and extend analytical and critical thinking skills developed throughout the two years through the study of applied issues and challenges faced by managers . The practical challenges are derived from case studies , from practical experiences offered through the unit , from interviews with a variety of ' expert ' managers representing diverse industrial sectors and from students ' own work experiences . Key practical ideas and skills include teamworking , personality profiling , decision-making , managing stress in the workplace and managing change . By the end of the unit , students will be able to relate theory to practice and will have a broad insight into the role of the manager and the challenges of management . <p> The unit aims to : <p> Integrate learning from earlier units so students become conversant in the issues and challenges regarding the management role in organisations today <p> Develop new knowledge and skills in analysis , option generation @ @ @ @ @ @ @ @ @ @ transition from theory to practice ; <p> Extend students ' knowledge of concepts of particular importance for practising managers , including psychometrics , stress in the workplace , leading in contemporary organisations , understanding change management , writing a business case , presentations interviewing , and team-working. ",
    "@@77495967 @6195967/ <h> Society Journal <p> The British Journal for the Philosophy of Science is published for the Society by Oxford University Press . Founded in 1950 , it is one of the leading international journals in the philosophy of science . It has a current Impact Factor of 1.281 ( and a 5-year impact factor of 1.465 ) , making it one of the highest cited journals in the field . Read more . <h> About the BSPS <p> The British Society for the Philosophy of Science ( BSPS ) is a professional society that furthers the study of the logic , the methods , and the philosophy of science , as well as those of the various special sciences , including the social sciences. - The BSPS- provides doctoral scholarships , small conference grants , and administers awards . It organises an annual conference for its members . The BSPS is also the professional society that administers the British Journal for the Philosophy of Science . Read more <p> Joining the BSPS allows you to attend the conference , apply for conference grants , receive society newsletters and email @ @ @ @ @ @ @ @ @ @ Learn about the benefits of joining the BSPS. ",
    "@@77495969 @6195969/ <p> We are pleased to announce the new IGRCT YouTube channel . Please click the title above to access recordings and excerpts of our public lectures . <p> West Front of the Parthenon , Athens . From  Views in Greece from Drawings  by Edward Dodwell ( 1821 ) . Image courtesy of Special Collections , University of Bristol Library <p> The IGRCT promotes research into all aspects of Greco-Roman culture from antiquity to the present day , in the belief that classical culture remains a vital influence in the modern world . It embraces research from many fields , including history of all kinds , archaeology , literary studies , art history and philosophy , and has a particular focus on research that explores the links between ancient and modern . <p> The Institute was formed in 2004 through the merger of the Bristol Institute of Hellenic and Roman Studies , founded in 2000 by Robert Fowler , and the Bristol Centre for the Classical Tradition , founded by the late Thomas Wiedemann . It achieves its aims by hiring postdoctoral research fellows and supporting their research @ @ @ @ @ @ @ @ @ @ holding symposia and conferences , cultivating international links with other scholars and organisations , and supporting the development of research projects in the faculty . <p> The work of the Institute would be impossible without the generous contributions of individual and corporate donors , and we would like to express our gratitude for their continued support . ",
    "@@77495970 @6195970/ <h> Queen 's School of Engineering <h> Welcome to the Queen 's School of Engineering <p> Undergraduate degree programmes in the School are arranged within the separate Departments of Aerospace , Civil and Mechanical Engineering , along with the interdisciplinary programme in Engineering Design . Our MEng undergraduates pursue professionally accredited specialised engineering programmes . They are also encouraged to study wider management , entrepreneurial and societal issues and to engage in original research and design activity . This combination of breadth and depth makes our graduates highly sought after by employers . ",
    "@@77495971 @6195971/ <h> July graduation 2017 <h> Important information <p> It is the responsibility of the graduand to read through and understand the information contained in the pages below and to contact the Graduation Office if you have any queries . <h> Security information <p> For the safety and peace of mind of our audiences , there will be additional security measures in place at our graduation ceremonies this year . We are unable to offer a cloakroom or storage facilities for large items of luggage , and bags may be subject to searches . We 'd recommend you allow extra time for queuing at the Wills Memorial Building and that you ensure all guests have their tickets . Please read the July 2017 graduation - security info ( PDF , 259kB ) for more information . <p> Please note that the date and time of your ceremony is included in your invitation email , and can also be found in the schedule of ceremonies below . ",
    "@@77495973 @6195973/ <h> About LLB Law <p> The University of Bristol Law School is a centre for an intellectually demanding , research-informed , legal education . We aim to produce accomplished , well-rounded , enquiring graduates with a rich , ethically grounded appreciation of law in business and society . <p> Our LLB programme is a three-year qualifying law degree . In the final year all students produce a 5,000-word project on a topic of their choice . The core and optional units reflect the wide variety of approaches to legal research adopted by the scholars in the Law School . <p> We are committed to the personal and professional development of our students , with small group teaching throughout . There is also an embedded law clinic programme that enables students to work on real life cases , with professional guidance and support . ",
    "@@77495975 @6195975/ <h> University ethical review <p> The University 's Ethics Policy and Procedure ( PDF , 154kB ) governs the ethics of research across the University of Bristol . It applies to all staff , students and anyone else carrying out research under the auspices of the University . All research that has ethical implications or involves human participants , their tissue and/or data must have an ethical review . <p> If research is undergoing an NHS or Social Care ethical review then secondary ethical review by the University is not required . ",
    "@@77495980 @6195980/ <h> English language requirements for study <p> You need to achieve a certain level of English to qualify for a place on your chosen course/programme . <p> Different courses/programmes need different levels of language skills . We refer to these skill levels as profiles . The profile for your chosen course/ programme is shown on the course/programme page . <p> The tests and levels you need to achieve each profile are on each profile page . <p> If a test is required , it should have been obtained within the last two years . <h> Applying <p> You do not need to have reached the required level before you apply . <p> We will look at your academic qualifications and decide what offer we will make you . If you have n't yet reached the required English level , we will give you a target grade in your offer . <h> What you need to do <h> If you have the required level <p> If you have the required level you must include it in your application . You do not need to do anything else . <h> If you @ @ @ @ @ @ @ @ @ @ you have n't reached the required level , you will be given a target grade in your offer . <p> You must tell us when you reach the target grade so we know you have met the requirement . <h> If you do n't  have the required level <p> If you do n't  have the required level you could try one of the following : ",
    "@@77495983 @6195983/ <h> Hire the pool <h> Swimming programmes <p> A varied range of programmes , catering for all standards of swimmers and various aquatic sports . Programme details . <h> Pay as you go swimming <p> Students , staff and members of the public can use the pool on a pay as you go basis for 4 per visit . In order to ensure we have a record of any medical conditions that may affect your ability to swim , and that you agree to the terms of use , we ask you to fill out a short form to use the pool on a pay as you go basis . We will issue you with a card which you can then show at reception each time you wish to payg swim . For more details see the memberships pages . ",
    "@@77495984 @6195984/ <h> Country specific information <p> The University of Bristol welcomes applications from international students , and accepts a wide range of qualifications for undergraduate and postgraduate study . If you studied at a school , college or university outside the UK , please select the relevant country page for further information on qualification equivalences , scholarships and details of our education representatives in your country . <p> Please note that entry requirements vary for each course so please check the course listings for details of specific entry requirements . <p> If your country or qualification is not listed please contact us and we will be able to advise you . "
]

def clean_and_normalize_text(text):
    # Remove numbers, special characters, and extra whitespace from the corpus
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\s+', ' ', text)  # Replace multiple spaces with a single space
    return text.strip().lower()

df = pd.DataFrame(corpus, columns=['text'])
df['text_clean'] = df['text'].apply(clean_and_normalize_text)

nlp = spacy.load('en_core_web_sm')

def lemmatize_text(text):
    doc = nlp(text)
    lemmatized_tokens = [token.lemma_ for token in doc if not token.is_stop and not token.is_punct]
    return ' '.join(lemmatized_tokens)

df['text_lemmatized'] = df['text_clean'].apply(lemmatize_text)

cv = CountVectorizer(stop_words='english',min_df=0.2, max_df=0.8)
X_cv = cv.fit_transform(df['text_lemmatized'])

print(pd.DataFrame(X_cv.toarray(), columns=cv.get_feature_names_out()))

tfv = TfidfVectorizer(stop_words='english',min_df=0.2, max_df=0.8)
X_tfv = tfv.fit_transform(df['text_lemmatized'])

print(pd.DataFrame(X_tfv.toarray(), columns=tfv.get_feature_names_out()))